@startuml
class ComputerFacade {
  -cpu: CPU
  -memory: Memory
  -disk: Disk
  +start()
}
class CPU { +freeze() +jump(position) +execute() }
class Memory { +load(position, data) }
class Disk { +read(sector, size) }

ComputerFacade *-- CPU
ComputerFacade *-- Memory
ComputerFacade *-- Disk
@enduml
